name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper nodejs npm jq curl

      - name: Build Debian package
        run: dpkg-buildpackage -us -uc

      - name: Move Debian packages
        run: |
          mkdir -p artifacts
          mv ../*.deb artifacts/
          mv ../*.buildinfo artifacts/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: artifacts/
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.deb
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
